### ISSUE TITLE
Calculate population percent from electoral, not general population

### ISSUE THREAD

**Issue by aneichyk** [tbicr/bel_pop#1]
Из Телеграм чата "Чат банка идей":
“есть переменная population_electoral в коде, но все группы считаются от общего population.” Надо переделать так чтобы population_ХХ_ХХ_p считалось делением на population_electoral а не на population как в данный момент.

![image](https://user-images.githubusercontent.com/19483696/86595368-e9670b00-bf98-11ea-923b-764233de140c.png)

Проценты в категориях слева должны суммироваться в 100%.

**Comment by tbicr** [comment]
памяняў
